### PR TITLE
find AnVIL assets

### PR DESCRIPTION
**Pull request by KatherineCox**
Trying to figure out why the tocless render can't find AnVIL assets

- The standard render works, just the tocless render fails
- It ran just fine in `AnVIL_Template` and `AnVIL_Book_WDL`.  Not sure why it's breaking here.

Troubleshooting
- Tried adding the assets in a separate PR, so they already exist, before updating _output.yml, but does not seem to have helped - still errors when I update _output.yml to point to the new location

### CODE REVIEW

**Comment by KatherineCox** [comment]
YES! I think I fixed it!!!

**Comment by KatherineCox** [comment]
@cansavvy I was having some trouble figuring out why this (moving the AnVIL assets to a subdirectory) was working in AnVIL_Template_Test and AnVIL_Book_WDL, but was not working when I tried to replicate it in this repo.

The problem occurs during the TOC-less render, specifically during `ottrpal::render_without_toc()`, if I try to put my css file in a subdirectory of `assets`.  The normal render can handle it, but the tocless render can't.

I think it's failing when it tries to copy *into* the preview's `assets/AnVIL_style` directory, because that destination directory doesn't exist.

But, if I first run a render using
- the old css, not in a subdirectory
- the new assets (logo, header, etc.) in a subdirectory

The subdirectory gets created and the logo, etc. get copied into it.

*Then* in a subsequent render I can move the css file to the subdirectory, and when `render_without_toc()` tries to copy it, it succeeds, because the destination directory already exists.

Not sure I explained that very well, and not sure it's worth putting in effort to make `render_without_toc()` more flexible, but, it took me a while to figure out, so I thought I'd share.

(In case you're wondering, the reason I wanted to move things to a subdirectory was so that I can have all the downstream repos sync the `assets/AnVIL_style` subdirectory without overwriting their whole `assets` directory)

**Comment by cansavvy** [comment]
> The problem occurs during the TOC-less render, specifically during `ottrpal::render_without_toc()`, if I try to put my css file in a subdirectory of `assets`.  The normal render can handle it, but the tocless render can't.
> 

Yes, you're correct. Unfortunately ottrpal isn't really flexible for the file path for the style.css file at the moment. Definitely something we can work on but I can't promise I will get to it quickly. I will file an issue though.

**Comment by KatherineCox** [comment]
> Definitely something we can work on but I can't promise I will get to it quickly. I will file an issue though.
@cansavvy No worries, I was able to figure out a solution that does what I need for `AnVIL_Template`.

**Pull request closed without merging**
