### PR TITLE
update-account-setup

### PR DESCRIPTION
**Pull request by ehumph**

### CODE REVIEW

**Comment by avahoffman** [comment]
Awesome @ehumph !

Looks like some funky indentation here:
image

4.3 - might be a good place for one of the css emphasis boxes!
5 - I might call this "Grouping Instructors and students"

What do you think about removing "Step #" from the headers? The sections are numbered so it feels a tad redundant.

**Comment by ehumph** [comment]
> Awesome @ehumph !
> 
> Looks like some funky indentation here: image
> 
> 4.3 - might be a good place for one of the css emphasis boxes! 5 - I might call this "Grouping Instructors and students"
> 
> What do you think about removing "Step #" from the headers? The sections are numbered so it feels a tad redundant.

Ooo, I like that idea! I wasn't completely sold on the formatting, but I couldn't quite put my finger on why. The billing commit will be coming soon (am going through Katie's billing videos)

**Comment by avahoffman** [comment]
Sounds good! Feel free to point to the videos where needed so you don't have to reinvent the wheel !

**Comment by avahoffman** [comment]
Apologies for the flurry of additions - was having some issues merging the new AnVIL template changes into this one.

**Review by avahoffman — APPROVED** [review]

**Pull request merged**
